# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88ad14bf256cfb534c0921b621490e64183206cae372f710b7ec2bdf60618aa11d53c53c8d9de973cc0585f229e7bf28f147cb7d75e670e3fc7243bd85d06edd

test:
  secret_key_base: cf42a2b1eaec2046d7783b90feb9e4546f4e6bfabb862a03d4d2ce9ba11aaad983b1acbf9ba52bc7f7f33ee62ec69673defe868f74a0b347dcd471ad90beaf6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
